oss:
  config:
    endpoint: "https://oss-cn-guangzhou.aliyuncs.com"
    bucket-name: "delivery-service-smzk"
    region: "cn-guangzhou"

spring:
  servlet:
    multipart:
      max-file-size: 50MB       # 单个文件最大大小
      max-request-size: 100MB   # 单次请求总数据大小
      enabled: true

  datasource:
    url : "jdbc:mysql://localhost:3306/delivery_service"
    password : 123456
    username : root

  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: 123456

wx:
  config:
    appid: "wxd3f33f213aea55a1"
    secret: "4989eed486407db5f75bc956cf274cb6"
    grant-type: "authorization_code"