spring:
  application:
    name: delivery-service-server
  datasource:
    url : "jdbc:mysql://localhost:3306/delivery_service"
    password : 123456
    username : root
  logging:
    file:
      name: ./app.log

# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
      group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.smzk.deliveryserviceserver.controller
  # knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn
mybatis-plus:
  global-config:
    db-config:
      id-type: AUTO
  mapper-locations: classpath:CurdXml/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

